### PR TITLE
added callback to catch

### PR DESCRIPTION
**Pull request by mxab**
Hi,

somehow it seems that the `catch` of the waitForUser promise is not that much into catching if it is not called with a catch handler

```
import angular from 'angular'
import 'angular-meteor'
import 'angular-meteor-auth'


angular.module('app',['angular-meteor','angular-meteor.auth'])
.run(function($auth,$log){
  $log.info('$auth testing');
  $auth.requireUser().then(u=>{
    $log.info('requireUser SUCCESS',u);
  }, err=>{
    $log.warn('requireUser ERROR',err);
  });
  $auth.waitForUser().then(u=>{
    $log.info('waitForUser SUCCESS',u);
  }, err=>{
    $log.warn('waitForUser ERROR',err);
  });
})

Meteor.startup(function(){
  angular.bootstrap(document.body, ['app']);
})
```
Has a the same result in my test app.

When I put in a handler like in the PR it works as expected.

### CODE REVIEW

**Comment by mxab** [comment]
@Urigo any thoughts on that?

**Comment by DAB0mB** [comment]
@mxab The job of `waitForUser` is just to return a promise and resolve it once the user has logged in, therefore it should not return any error. Does it make any sense? Well it's not even something to discuss about since it only exists to implement an older API of `angular-meteor-auth`. Instead I recommend using `awaitUser` which was implemented in the new API and it the functionalities of `waitForUser`, `requireUser` and `requireValidUser` all at once. For more information see [our docs page](http://www.angular-meteor.com/api/1.3.6/auth).

**Comment by mxab** [comment]
@DAB0mB I'm quite aware of what `waitForUser` does, you got me wrong. My problem is that they currently act the same
both result in error if there is no user

See this sample application
https://github.com/mxab/angular-meteor-auth-issue/blob/master/client/main.js

The log output is:
```
$auth testing
requireUser ERROR AUTH_REQUIRED
waitForUser ERROR AUTH_REQUIRED
```
About the awaitForUser, sure I could use this as well and simply create my own waitFor/requireUser wrappers around it but why should I if this package provides it already. I actually thought they weren't simply in the docs, since the one you pointed out is about 0.3.0 and the current one is 1.0.0

**Comment by DAB0mB** [comment]
Hey, I referenced a pull request which should fix this issue. Can you please confirm it that the issue has been fixed? It would be great!

**Comment by mxab** [comment]
Sure, I'll give it a try.
Two things tough, at one point someone should figure out why the catch with no handler results in not catching it and the the point is just a very personal opinion that catch blocks should never silently swallow stuff as it might give debugging nightmares (I'm talking to you Blaze), that was the reason it put a debug log there

**Comment by Urigo** [comment]
was addressed here:  https://github.com/Urigo/angular-meteor-auth/pull/23

**Pull request closed without merging**
